# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tjBECnuUJR4ahCP8JjqZrdItaPsWFsm3
"""

# =========================
# IMPORT LIBRARIES
# =========================

import torch
import torchvision
import torch.nn as nn
import torch.optim as optim
from torchvision import transforms
from torch.utils.data import DataLoader
import math
import matplotlib.pyplot as plt


# =========================
# DEVICE
# =========================

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)


# =========================
# HYPERPARAMETERS
# =========================

T = 1000
img_size = 32
batch_size = 128
base_channels = 64
epochs = 150
lr_rate = 1e-4


# =========================
# DATASET
# =========================

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.5,0.5,0.5],
        std=[0.5,0.5,0.5]
    )
])

train_dataset = torchvision.datasets.CIFAR10(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)


# =========================
# DIFFUSION SCHEDULE
# =========================

betas = torch.linspace(1e-4, 0.02, T).to(device)

alphas = 1.0 - betas

alpha_bar = torch.cumprod(alphas, dim=0)


# =========================
# FORWARD DIFFUSION
# =========================

def forward_diffusion(x0, t):

    noise = torch.randn_like(x0)

    sqrt_alpha_bar = torch.sqrt(alpha_bar[t])[:, None, None, None]

    sqrt_one_minus_alpha_bar = torch.sqrt(
        1 - alpha_bar[t]
    )[:, None, None, None]

    xt = sqrt_alpha_bar * x0 + sqrt_one_minus_alpha_bar * noise

    return xt, noise


# =========================
# TIME EMBEDDING
# =========================

class TimeEmbedding(nn.Module):

    def __init__(self, dim):
        super().__init__()

        self.dim = dim

    def forward(self, t):

        half_dim = self.dim // 2

        freqs = torch.exp(
            -math.log(10000) *
            torch.arange(half_dim, device=t.device)
            / (half_dim - 1)
        )

        args = t[:, None] * freqs[None, :]

        embedding = torch.cat(
            [torch.sin(args), torch.cos(args)],
            dim=1
        )

        return embedding


# =========================
# RESIDUAL BLOCK
# =========================

class ResidualBlock(nn.Module):

    def __init__(self, in_ch, out_ch, time_dim):

        super().__init__()

        self.norm1 = nn.GroupNorm(32, in_ch)

        self.conv1 = nn.Conv2d(
            in_ch,
            out_ch,
            kernel_size=3,
            padding=1
        )

        self.time_mlp = nn.Linear(time_dim, out_ch)

        self.norm2 = nn.GroupNorm(32, out_ch)

        self.conv2 = nn.Conv2d(
            out_ch,
            out_ch,
            kernel_size=3,
            padding=1
        )

        self.skip = (
            nn.Conv2d(in_ch, out_ch, kernel_size=1)
            if in_ch != out_ch
            else nn.Identity()
        )

    def forward(self, x, t):

        h = self.norm1(x)
        h = torch.relu(h)

        h = self.conv1(h)

        time_embedding = self.time_mlp(t)

        h = h + time_embedding[:, :, None, None]

        h = self.norm2(h)
        h = torch.relu(h)

        h = self.conv2(h)

        return h + self.skip(x)


# =========================
# ATTENTION BLOCK
# =========================

class AttentionBlock(nn.Module):

    def __init__(self, ch):

        super().__init__()

        self.norm = nn.GroupNorm(32, ch)

        self.q = nn.Conv2d(ch, ch, kernel_size=1)
        self.k = nn.Conv2d(ch, ch, kernel_size=1)
        self.v = nn.Conv2d(ch, ch, kernel_size=1)

        self.proj = nn.Conv2d(ch, ch, kernel_size=1)

    def forward(self, x):

        B, C, H, W = x.shape

        h = self.norm(x)

        q = self.q(h).reshape(B, C, H * W)
        k = self.k(h).reshape(B, C, H * W)
        v = self.v(h).reshape(B, C, H * W)

        # attention scores
        attn = torch.einsum(
            "bcn,bcm->bnm",
            q,
            k
        ) / math.sqrt(C)

        attn = torch.softmax(attn, dim=-1)

        # weighted sum
        h = torch.einsum(
            "bnm,bcm->bcn",
            attn,
            v
        )

        h = h.reshape(B, C, H, W)

        h = self.proj(h)

        return x + h


# =========================
# DDPM U-NET
# =========================

class DDPM(nn.Module):

    def __init__(self):

        super().__init__()

        time_dim = base_channels * 4

        # =====================
        # TIME EMBEDDING
        # =====================

        self.time_mlp = nn.Sequential(
            TimeEmbedding(base_channels),

            nn.Linear(base_channels, time_dim),

            nn.ReLU(),

            nn.Linear(time_dim, time_dim)
        )

        # =====================
        # INPUT
        # =====================

        self.conv_in = nn.Conv2d(
            3,
            base_channels,
            kernel_size=3,
            padding=1
        )

        # =====================
        # DOWN
        # =====================

        self.down1 = ResidualBlock(
            base_channels,
            base_channels,
            time_dim
        )

        self.pool1 = nn.AvgPool2d(2)

        self.down2 = ResidualBlock(
            base_channels,
            base_channels * 2,
            time_dim
        )

        self.pool2 = nn.AvgPool2d(2)

        self.down3 = ResidualBlock(
            base_channels * 2,
            base_channels * 4,
            time_dim
        )

        # =====================
        # MIDDLE
        # =====================

        self.mid1 = ResidualBlock(
            base_channels * 4,
            base_channels * 4,
            time_dim
        )

        self.attn = AttentionBlock(
            base_channels * 4
        )

        self.mid2 = ResidualBlock(
            base_channels * 4,
            base_channels * 4,
            time_dim
        )

        # =====================
        # UP
        # =====================

        self.up_s1 = nn.Upsample(
            scale_factor=2,
            mode='nearest'
        )

        self.up1 = ResidualBlock(
            base_channels * 6,     # 256 + 128
            base_channels * 2,     # 128
            time_dim
        )

        # =====================
        # EXTRA ATTENTION
        # =====================

        self.attn_up = AttentionBlock(base_channels * 2)

        self.up_s2 = nn.Upsample(
            scale_factor=2,
            mode='nearest'
        )

        self.up2 = ResidualBlock(
            base_channels * 3,     # 128 + 64
            base_channels,         # 64
            time_dim
        )

        # =====================
        # OUTPUT
        # =====================

        self.conv_out = nn.Conv2d(
            base_channels,
            3,
            kernel_size=3,
            padding=1
        )

    def forward(self, x, t):

        # =====================
        # TIME EMBEDDING
        # =====================

        t = self.time_mlp(t.float())

        # =====================
        # INPUT
        # =====================

        x = self.conv_in(x)

        # =====================
        # DOWN
        # =====================

        d1 = self.down1(x, t)

        h = self.pool1(d1)

        d2 = self.down2(h, t)

        h = self.pool2(d2)

        h = self.down3(h, t)

        # =====================
        # MIDDLE
        # =====================

        h = self.mid1(h, t)

        h = self.attn(h)

        h = self.mid2(h, t)

        # =====================
        # UP STAGE 1
        # =====================

        h = self.up_s1(h)

        h = torch.cat(
            [h, d2],
            dim=1
        )

        h = self.up1(h, t)

        h = self.attn_up(h)

        # =====================
        # UP STAGE 2
        # =====================

        h = self.up_s2(h)

        h = torch.cat(
            [h, d1],
            dim=1
        )

        h = self.up2(h, t)

        # =====================
        # OUTPUT
        # =====================

        h = self.conv_out(h)

        return h



# =========================
# MODEL
# =========================

model = DDPM().to(device)

optimizer = optim.AdamW(
    model.parameters(),
    lr=lr_rate
)


# =========================
# TRAINING LOOP
# =========================

for epoch in range(epochs):

    model.train()

    total_loss = 0

    for x, _ in train_loader:

        x = x.to(device)

        # random timestep
        t = torch.randint(
            0,
            T,
            (x.shape[0],),
            device=device
        )

        # forward diffusion
        xt, noise = forward_diffusion(x, t)

        # predict noise
        noise_pred = model(xt, t)

        # MSE loss
        loss = ((noise_pred - noise) ** 2).mean()

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)

    print(f"Epoch {epoch+1}/{epochs} | Loss: {avg_loss:.4f}")

# =========================
# SAMPLING
# =========================

@torch.no_grad()
def sample(model, n_samples=16):

    model.eval()

    # start from pure noise
    x = torch.randn(
        n_samples,
        3,
        img_size,
        img_size
    ).to(device)

    for t in reversed(range(T)):

        t_batch = torch.full(
            (n_samples,),
            t,
            device=device,
            dtype=torch.long
        )

        # predict noise
        noise_pred = model(x, t_batch)

        alpha = alphas[t]
        alpha_hat = alpha_bar[t]
        beta = betas[t]

        if t > 0:
            z = torch.randn_like(x)
        else:
            z = torch.zeros_like(x)

        x = (
            1 / torch.sqrt(alpha)
        ) * (
            x -
            ((1 - alpha) /
             torch.sqrt(1 - alpha_hat))
            * noise_pred
        ) + torch.sqrt(beta) * z

    return x

# generate samples
samples = sample(model, 16)

samples = (samples + 1) / 2
samples = samples.clamp(0, 1)

# =========================
# SHOW IMAGES
# =========================

fig, axes = plt.subplots(4, 4, figsize=(6, 6))

for i, ax in enumerate(axes.flatten()):

    img = samples[i].cpu()

    # Convert from (C,H,W) -> (H,W,C)
    img = img.permute(1, 2, 0)

    ax.imshow(img)
    ax.axis('off')

plt.tight_layout()
plt.show()

!pip install torch-fidelity

from torchvision.utils import save_image
import os

os.makedirs("fake_images", exist_ok=True)

for i, img in enumerate(samples):
    save_image(img.cpu(), f"fake_images/{i}.png")

from torchvision.datasets import CIFAR10
from torchvision import transforms

testset = CIFAR10(
    root='./data',
    train=False,
    download=True,
    transform=transforms.ToTensor()
)

os.makedirs("real_images", exist_ok=True)

for i in range(16):
    img, _ = testset[i]
    save_image(img, f"real_images/{i}.png")

from torch_fidelity import calculate_metrics

metrics = calculate_metrics(
    input1="real_images",
    input2="fake_images",
    fid=True,
    cuda=True
)

print(metrics["frechet_inception_distance"])

